# Generated by Django 3.2.8 on 2022-04-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('user_log_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=30, null=True)),
                ('target_url', models.CharField(max_length=300, null=True)),
                ('youtube_id', models.CharField(max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_log',
            },
        ),
    ]
