# Generated by Django 3.2.8 on 2022-05-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpCount',
            fields=[
                ('ip_count_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=30, null=True)),
                ('count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ip_count',
            },
        ),
    ]
