# Generated by Django 3.2.8 on 2022-07-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('request_status_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('word_cloud_status', models.BooleanField(default=False)),
                ('word_analysis_status', models.BooleanField(default=False)),
            ],
        ),
    ]
