# Generated by Django 3.2.8 on 2022-07-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userlog_thread_ident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='thread_ident',
            field=models.IntegerField(default=0),
        ),
    ]
