# Generated by Django 3.2.8 on 2022-07-05 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCloud',
            fields=[
                ('word_cloud_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('weight', models.IntegerField(default=0)),
                ('user_log_idx', models.ForeignKey(db_column='user_log_idx', on_delete=django.db.models.deletion.RESTRICT, related_name='word_cloud_user_log_idx', to='main.userlog')),
            ],
            options={
                'db_table': 'word_cloud',
            },
        ),
        migrations.CreateModel(
            name='WordAnalysis',
            fields=[
                ('word_analysis_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('positive_proportion', models.FloatField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('word_cloud_idx', models.ForeignKey(db_column='word_cloud_idx', on_delete=django.db.models.deletion.RESTRICT, related_name='word_analysis_word_cloud', to='analysis.wordcloud')),
            ],
            options={
                'db_table': 'word_analysis',
            },
        ),
        migrations.CreateModel(
            name='CommentAnalysis',
            fields=[
                ('comment_analysis_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_img', models.CharField(max_length=300, null=True)),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('comment', models.TextField(max_length=10000)),
                ('sentence', models.TextField(max_length=10000)),
                ('positive', models.BooleanField(default=True)),
                ('word_cloud_idx', models.ForeignKey(db_column='word_cloud_idx', on_delete=django.db.models.deletion.RESTRICT, related_name='comment_analysis_word_cloud', to='analysis.wordcloud')),
            ],
            options={
                'db_table': 'comment_analysis',
            },
        ),
        migrations.CreateModel(
            name='ActiveInfo',
            fields=[
                ('active_info_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('active_proportion', models.FloatField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('user_log_idx', models.ForeignKey(db_column='user_log_idx', on_delete=django.db.models.deletion.RESTRICT, related_name='active_info_user_log_idx', to='main.userlog')),
            ],
            options={
                'db_table': 'active_info',
            },
        ),
    ]
